version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  faktory:
    image: contribsys/faktory
    environment:
      - FAKTORY_PASSWORD=S5c9qeRksjwcQEgScQuc8nHPgdRwS9uf
    ports:
      - '7419:7419'
      - '7420:7420'
volumes:
  postgres:
